apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "my-project.fullname" . }}
    chart: {{ template "my-project.chart" . }}
    component: {{ template "my-project.fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ template "my-project.fullname" . }}
  name: {{ template "my-project.fullname" . }}-environment-properties
data:
{{- range $key, $value := index .Values.files "environment.properties" }}
  {{ $key }} : {{ $value | quote }}
{{- end }}
