{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "my-project.fullname" . }}
    chart: {{ template "my-project.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ template "my-project.fullname" . }}
  name: {{ template "my-project.fullname" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ template "my-project.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ . }}
  {{- end }}
{{- end }}
